In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [3]:
MD_agric_df = pd.read_csv("MD_agric_exam-4313.csv")

In [8]:
MD_agric_df

,Field_ID,Elevation,Rainfall,Min_temperature_C,Max_temperature_C,pH,Pollution_level,Plot_size,Annual_yield,Crop_type
0,1162,494.95615,1507.6,-5.4,31.0,6.859436,0.007034,3.6,1.617421,coffee
1,5108,663.73390,581.0,-4.7,30.9,5.603219,0.289643,4.2,2.532497,potato
2,3504,396.87990,1715.1,-6.1,31.7,5.774116,0.000409,2.6,1.262207,banana
3,5351,594.80370,1748.0,-4.3,33.6,6.477415,0.088777,7.9,4.351564,wheat
4,905,609.49800,1395.8,-4.5,31.3,5.419586,0.050023,10.8,5.034791,cassava
...,...,...,...,...,...,...,...,...,...,...
995,2202,572.95935,625.6,-5.5,31.0,5.258964,0.086330,1.2,0.750675,wheat
996,2531,552.80945,398.1,-5.9,33.4,4.607136,0.130178,0.8,0.449790,wheat
997,1040,678.22504,564.4,-4.6,31.7,5.567556,0.448149,1.2,0.492988,maize
998,58,792.65370,928.5,-3.3,31.2,5.102048,0.387350,1.1,0.597557,potato
999,3334,747.69850,981.5,-3.7,31.0,6.715882,0.541706,11.1,2.867815,coffee

In [25]:
total_rainfall = MD_agric_df.groupby(MD_agric_df['Pollution_level']>0.2)['Rainfall'].sum()
total_rainfall

Pollution_level
False    718832.1
True     478902.6
Name: Rainfall, dtype: float64

In [26]:
MD_agric_df['High_pollution'] = MD_agric_df['Pollution_level'] > 0.2

total_rainfall = MD_agric_df.groupby('High_pollution')['Rainfall'].sum()

total_rainfall

High_pollution
False    718832.1
True     478902.6
Name: Rainfall, dtype: float64

In [12]:
MD_agric_df['Crop_type'].nunique()

8

In [23]:
max_wheat_yield = round(MD_agric_df.loc[
    MD_agric_df['Crop_type'] == 'wheat',
    'Annual_yield'
].max(), 2)

max_wheat_yield

8.99

In [35]:
def temperature_range(field_id):
    
    min_temp = MD_agric_df.loc[
        MD_agric_df['Field_ID'] == field_id,
        'Min_temperature_C'
    ].min()

    max_temp = MD_agric_df.loc[
        MD_agric_df['Field_ID'] == field_id,
        'Max_temperature_C'
    ].max()


    
    temp_range = max_temp - min_temp
    
    return temp_range

range_1458 = temperature_range(1458)
range_1895 = temperature_range(1895)
range_5443 = temperature_range(5443)

answers = (range_1458, range_1895, range_5443)
answers

(40.7, 35.7, 33.4)

In [36]:
MD_agric_df

,Field_ID,Elevation,Rainfall,Min_temperature_C,Max_temperature_C,pH,Pollution_level,Plot_size,Annual_yield,Crop_type,High_pollution
0,1162,494.95615,1507.6,-5.4,31.0,6.859436,0.007034,3.6,1.617421,coffee,False
1,5108,663.73390,581.0,-4.7,30.9,5.603219,0.289643,4.2,2.532497,potato,True
2,3504,396.87990,1715.1,-6.1,31.7,5.774116,0.000409,2.6,1.262207,banana,False
3,5351,594.80370,1748.0,-4.3,33.6,6.477415,0.088777,7.9,4.351564,wheat,False
4,905,609.49800,1395.8,-4.5,31.3,5.419586,0.050023,10.8,5.034791,cassava,False
...,...,...,...,...,...,...,...,...,...,...,...
995,2202,572.95935,625.6,-5.5,31.0,5.258964,0.086330,1.2,0.750675,wheat,False
996,2531,552.80945,398.1,-5.9,33.4,4.607136,0.130178,0.8,0.449790,wheat,False
997,1040,678.22504,564.4,-4.6,31.7,5.567556,0.448149,1.2,0.492988,maize,True
998,58,792.65370,928.5,-3.3,31.2,5.102048,0.387350,1.1,0.597557,potato,True
999,3334,747.69850,981.5,-3.7,31.0,6.715882,0.541706,11.1,2.867815,coffee,True

In [40]:
MD_agric_df.loc[
    MD_agric_df['pH'] < 5.5,
    'Plot_size'
].sum()

np.float64(1731.8999999999999)

In [42]:
Temp_less_65 = MD_agric_df.loc[
    (MD_agric_df['Min_temperature_C'] < -5) &
    (MD_agric_df['Max_temperature_C'] > 30)]

Temp_less_65

,Field_ID,Elevation,Rainfall,Min_temperature_C,Max_temperature_C,pH,Pollution_level,Plot_size,Annual_yield,Crop_type,High_pollution
0,1162,494.95615,1507.6,-5.4,31.0,6.859436,0.007034,3.6,1.617421,coffee,False
2,3504,396.87990,1715.1,-6.1,31.7,5.774116,0.000409,2.6,1.262207,banana,False
5,2274,270.45100,1665.2,-7.2,34.3,5.873082,0.001545,3.9,1.743458,banana,False
13,4807,520.29770,292.3,-6.3,32.9,5.379286,0.196589,1.4,0.881568,potato,False
14,973,432.03570,1464.4,-6.0,30.2,7.482802,0.019800,3.0,1.377434,wheat,False
...,...,...,...,...,...,...,...,...,...,...,...
990,1637,504.66306,1144.5,-5.7,32.1,5.666609,0.431891,4.8,2.486276,wheat,True
991,756,578.91270,889.4,-5.2,31.0,5.062155,0.442495,2.2,1.209928,cassava,True
992,1332,359.76013,1816.0,-6.4,32.9,7.350705,0.133453,2.9,1.225715,wheat,False
995,2202,572.95935,625.6,-5.5,31.0,5.258964,0.086330,1.2,0.750675,wheat,False
996,2531,552.80945,398.1,-5.9,33.4,4.607136,0.130178,0.8,0.449790,wheat,False

In [46]:
np.std(MD_agric_df['Rainfall'].loc[
    MD_agric_df['Plot_size'] > np.median(MD_agric_df['Plot_size'])
])

469.6199685856172

In [56]:
total = 0

for crop in MD_agric_df['Crop_type'].unique():
    total += len(crop)

total

42